#use "base.decls"

typedef NAME = UPPERCASE (LOWERCASE)* ;;
typedef UPPERCASENAME = UPPERCASE (UPPERCASE)*;;

typedef LASTCOMMAFIRST = UPPERCASENAME ", " UPPERCASENAME ", " UPPERCASENAME ", " UPPERCASENAME;;
typedef FIRSTTHENLAST = NAME " " NAME " " NAME " " NAME;;

capitalize = [LASTCOMMAFIRST <=> FIRSTTHENLAST
{}]
